#!/usr/bin/env bash
set -ex

mkdir -p $HOME/bin
export PATH=$HOME/bin:$PATH

case "$*" in

 jitpack)
   mill -i __.publishM2Local
 ;;


 "jitpack deps")
     # asdf depends on column and asdf-java depends on jq,
     # however it seems there's no way to install system dependencies on jitpack container.
     # We just install mill and set a jdk on jitpack.yml
     echo installing mill via curl
     mill_version=$(awk '/mill/ {print $2}' .tool-versions)
     curl -o $HOME/bin/mill -L https://github.com/lihaoyi/mill/releases/download/$mill_version/$mill_version
     chmod +x $HOME/bin/mill
 ;;


 test)
   mill -i __.publishLocal
   (cd example; mill -i hello.dockerBuild)
   docker run -i hello:latest
 ;;

esac
