#!/usr/bin/env bash
set -ex

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function die {
  echo "$*" >&2
  exit 1
}

case "$1" in

 jitpack)
   exec $0 mill -j 0 __.publishM2Local
 ;;

 mill)
   exec $0 cs launch --jvm graalvm:19.0.2 --scala 2.13.3 mill -- "${@:2}"
 ;;

 mill-i)
   exec $0 cs launch --jvm graalvm:19.0.2 --scala 2.13.3 mill-interactive -- -i "${@:2}"
 ;;

 scalafmt)
   exec $0 cs launch --jvm graalvm:19.0.2 --scala 2.13.3 scalafmt -- --mode diff --diff-branch master "${@:2}"
 ;;

 scalafmt-test)
   $0 scalafmt --test
 ;;

 cs)
   test -x $BASE_DIR/cs || {
     curl -o $BASE_DIR/cs -qL https://git.io/coursier-cli
     chmod +x $BASE_DIR/cs
   }
   exec $BASE_DIR/cs "${@:2}"
 ;;

 example)
  $0 mill-i -j 0 -D PUBLISH_VERSION=latest __.publishLocal
  (cd example; ../ci mill hello.dockerBuild)
  docker run -i hello:latest
 ;;

 test)
   $0 mill -j 0 __.tests
 ;;

 release)
   git tag $(<VERSION)
   git push --tags
 ;;

 *)
  die "Command not found ${@}"
 ;;

esac
